FROM docker.io/library/alpine:${com.io7m.oci.versionAlpine}
FROM docker.io/library/eclipse-temurin:${com.io7m.oci.versionTemurin}

ENV PATH="/cardant/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/java/openjdk/bin"
ENV CARDANT_HOME="/cardant"

COPY cardant /cardant

LABEL "org.opencontainers.image.authors"="Mark Raynsford"
LABEL "org.opencontainers.image.description"="Inventory system"
LABEL "org.opencontainers.image.licenses"="ISC"
LABEL "org.opencontainers.image.source"="https://www.github.com/io7m/cardant"
LABEL "org.opencontainers.image.title"="Cardant"
LABEL "org.opencontainers.image.url"="https://www.io7m.com/software/cardant"
LABEL "org.opencontainers.image.version"="${project.version}"
LABEL "org.opencontainers.image.revision"="${buildNumber}"

ENTRYPOINT ["/cardant/bin/cardant"]
