#!/bin/sh

if [ -z "${CARDANT_HOME}" ]
then
  echo "CARDANT_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${CARDANT_HOME}/lib" \
-m com.io7m.cardant.main/com.io7m.cardant.main.CAServerMain \
"$@"
