/*
 * Copyright © 2023 Mark Raynsford <code@io7m.com> https://www.io7m.com
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

import com.io7m.cardant.tests.arbitraries.*;
import com.io7m.cardant.tests.arbitraries.model.*;
import net.jqwik.api.providers.ArbitraryProvider;

/**
 * Inventory server (Arbitrary instances)
 */

module com.io7m.cardant.tests.arbitraries
{
  requires static org.osgi.annotation.bundle;
  requires static org.osgi.annotation.versioning;

  requires com.io7m.cardant.protocol.inventory;

  requires net.jqwik.api;

  exports com.io7m.cardant.tests.arbitraries;
  exports com.io7m.cardant.tests.arbitraries.model;

  uses ArbitraryProvider;

  provides ArbitraryProvider with
CAArbAttachment,
CAArbAttachmentKey,
CAArbAuditEvent,
CAArbAuditSearchParameters,
CAArbCommand,
CAArbCommandAuditSearchBegin,
CAArbCommandAuditSearchNext,
CAArbCommandAuditSearchPrevious,
CAArbCommandDebugInvalid,
CAArbCommandDebugRandom,
CAArbCommandFileGet,
CAArbCommandFilePut,
CAArbCommandFileRemove,
CAArbCommandFileSearchBegin,
CAArbCommandFileSearchNext,
CAArbCommandFileSearchPrevious,
CAArbCommandItemAttachmentAdd,
CAArbCommandItemAttachmentRemove,
CAArbCommandItemCreate,
CAArbCommandItemDelete,
CAArbCommandItemGet,
CAArbCommandItemLocationsList,
CAArbCommandItemMetadataPut,
CAArbCommandItemMetadataRemove,
CAArbCommandItemReposit,
CAArbCommandItemSearchBegin,
CAArbCommandItemSearchNext,
CAArbCommandItemSearchPrevious,
CAArbCommandItemSetName,
CAArbCommandItemTypesAssign,
CAArbCommandItemTypesRevoke,
CAArbCommandLocationAttachmentAdd,
CAArbCommandLocationAttachmentRemove,
CAArbCommandLocationDelete,
CAArbCommandLocationGet,
CAArbCommandLocationList,
CAArbCommandLocationMetadataPut,
CAArbCommandLocationMetadataRemove,
CAArbCommandLocationPut,
CAArbCommandLocationTypesAssign,
CAArbCommandLocationTypesRevoke,
CAArbCommandLogin,
CAArbCommandRolesAssign,
CAArbCommandRolesGet,
CAArbCommandRolesRevoke,
CAArbCommandTypePackageGetText,
CAArbCommandTypePackageInstall,
CAArbCommandTypePackageSearchBegin,
CAArbCommandTypePackageSearchNext,
CAArbCommandTypePackageSearchPrevious,
CAArbCommandTypePackageUninstall,
CAArbCommandTypePackageUpgrade,
CAArbDescriptionMatch,
CAArbDottedName,
CAArbErrorCode,
CAArbFile,
CAArbFileColumnOrdering,
CAArbFileID,
CAArbFileSearchParameters,
CAArbFileWithoutData,
CAArbIdName,
CAArbIds,
CAArbItem,
CAArbItemColumnOrdering,
CAArbItemID,
CAArbItemLocation,
CAArbItemLocations,
CAArbItemReposit,
CAArbItemRepositSerialAdd,
CAArbItemRepositSerialMove,
CAArbItemRepositSerialRemove,
CAArbItemRepositSetAdd,
CAArbItemRepositSetMove,
CAArbItemRepositSetRemove,
CAArbItemSearchParameters,
CAArbItemSerial,
CAArbItemSummary,
CAArbListLocationAll,
CAArbListLocationBehaviour,
CAArbListLocationExact,
CAArbListLocationWithDescendants,
CAArbLocation,
CAArbLocationID,
CAArbLocationSummaries,
CAArbLocationSummary,
CAArbMRoleName,
CAArbMediaTypeMatch,
CAArbMetadata,
CAArbMetadataElementMatch,
CAArbMetadataElementMatchAnd,
CAArbMetadataElementMatchOr,
CAArbMetadataElementMatchSpecific,
CAArbMetadataIntegral,
CAArbMetadataMonetary,
CAArbMetadataReal,
CAArbMetadataText,
CAArbMetadataTime,
CAArbMetadataValueMatch,
CAArbMetadataValueMatchAnything,
CAArbMetadataValueMatchIntegral,
CAArbMetadataValueMatchIntegralWithinRange,
CAArbMetadataValueMatchMonetary,
CAArbMetadataValueMatchMonetaryWithCurrency,
CAArbMetadataValueMatchMonetaryWithinRange,
CAArbMetadataValueMatchReal,
CAArbMetadataValueMatchRealWithinRange,
CAArbMetadataValueMatchText,
CAArbMetadataValueMatchTextExact,
CAArbMetadataValueMatchTextSearch,
CAArbMetadataValueMatchTime,
CAArbMetadataValueMatchTimeWithinRange,
CAArbNameMatch,
CAArbOffsetDateTime,
CAArbResponse,
CAArbResponseAuditSearch,
CAArbResponseError,
CAArbResponseFileGet,
CAArbResponseFilePut,
CAArbResponseFileRemove,
CAArbResponseFileSearch,
CAArbResponseItemAttachmentAdd,
CAArbResponseItemAttachmentRemove,
CAArbResponseItemCreate,
CAArbResponseItemDelete,
CAArbResponseItemGet,
CAArbResponseItemLocationsList,
CAArbResponseItemMetadataPut,
CAArbResponseItemMetadataRemove,
CAArbResponseItemReposit,
CAArbResponseItemSearch,
CAArbResponseItemSetName,
CAArbResponseItemTypesAssign,
CAArbResponseItemTypesRevoke,
CAArbResponseLocationAttachmentAdd,
CAArbResponseLocationAttachmentRemove,
CAArbResponseLocationGet,
CAArbResponseLocationList,
CAArbResponseLocationMetadataPut,
CAArbResponseLocationMetadataRemove,
CAArbResponseLocationPut,
CAArbResponseLocationDelete,
CAArbResponseLocationTypesAssign,
CAArbResponseLocationTypesRevoke,
CAArbResponseLogin,
CAArbResponseRolesAssign,
CAArbResponseRolesGet,
CAArbResponseRolesRevoke,
CAArbResponseTypePackageGetText,
CAArbResponseTypePackageInstall,
CAArbResponseTypePackageSearch,
CAArbResponseTypePackageUninstall,
CAArbResponseTypePackageUpgrade,
CAArbSizeRange,
CAArbTimeRange,
CAArbTypeDeclaration,
CAArbTypeDeclarationSearchParameters,
CAArbTypeDeclarationSummary,
CAArbTypeField,
CAArbTypeMatch,
CAArbTypePackageIdentifier,
CAArbTypePackageSearchParameters,
CAArbTypePackageSummary,
CAArbTypePackageUninstall,
CAArbTypeRecordFieldIdentifier,
CAArbTypeRecordIdentifier,
CAArbTypeScalar,
CAArbTypeScalarIntegral,
CAArbTypeScalarMonetary,
CAArbTypeScalarReal,
CAArbTypeScalarSearchParameters,
CAArbTypeScalarText,
CAArbTypeScalarTime,
CAArbUserID,
CAArbVersion
    ;
}
